#include <doctest/doctest.h>

#include "json_io.h"
#include "process.h"
#include "test_support.h"

#include <filesystem>
#include <string>

// differential parity against cpython.
//
// tests/fixtures/json_parity.json is generated by scripts/make_parity_corpus.py
// and holds, for each value, the exact bytes harness/io.py would leave on disk.
// this is the check that keeps the two implementations interchangeable while
// both exist; regenerate the fixture rather than editing it.
TEST_CASE("json_serialize reproduces cpython byte for byte")
{
	const std::filesystem::path fixture =
	  std::filesystem::path(ODIN_FIXTURES) / "json_parity.json";

	odin_error err;
	const json corpus = json_read(fixture, err);
	REQUIRE_FALSE(failed(err));

#ifdef _WIN32
	const char *expected_linesep = "crlf";
#else
	const char *expected_linesep = "lf";
#endif
	// a corpus generated on another platform would fail every case for one
	// uninformative reason, so say so plainly instead.
	REQUIRE_MESSAGE(corpus.at("linesep") == expected_linesep,
					"parity corpus was generated on a different platform; "
					"re-run scripts/make_parity_corpus.py");

	REQUIRE(corpus.at("cases").is_array());
	REQUIRE_FALSE(corpus.at("cases").empty());

	for (const json &item : corpus.at("cases"))
	{
		const std::string name = item.at("name").get<std::string>();
		const std::string expected = item.at("expected").get<std::string>();

		CAPTURE(name);
		CHECK(json_serialize(item.at("value")) == expected);
	}
}

// every subprocess call in the harness decodes with errors="replace", and the
// text lands in json state files. the number of u+fffd is not obvious - cpython
// follows the unicode "maximal subpart" rule, so b"\xe0\x80\xaf" yields three
// replacements rather than one - so it is pinned against cpython here too.
TEST_CASE("utf8_sanitize reproduces cpython's errors=replace")
{
	const std::filesystem::path fixture = std::filesystem::path(ODIN_FIXTURES) / "json_parity.json";

	odin_error err;
	const json corpus = json_read(fixture, err);
	REQUIRE_FALSE(failed(err));
	REQUIRE(corpus.contains("utf8_cases"));

	for (const json &item : corpus.at("utf8_cases"))
	{
		const std::string name = item.at("name").get<std::string>();
		const std::string expected = item.at("expected").get<std::string>();

		std::string raw;
		for (const json &byte : item.at("bytes"))
		{
			raw.push_back(static_cast<char>(byte.get<int>()));
		}

		CAPTURE(name);
		CHECK(utf8_sanitize(raw) == expected);
	}
}
